### ISSUE TITLE
iPhone stops reporting randomly

### ISSUE THREAD

**Issue by nickelnine** [ESPresense/ESPresense#234] opened 2022-02-10 05:05 UTC
**Describe the bug**
iPhone 12 Pro went not_home all of a sudden and has not gone back to bedroom like it was doing earlier today. It is currently 10PM MST and the last reported message in MQTT Explorer is from 9:47PM and the phone is a little more than a meter from the ESP32. I launched room-assistant app and immediately saw MQTT messages pouring in but when I configured mqtt_room in HA and rebooted, the MQTT messages stopped arriving for room-assistant. Both methods are frozen and nothing in MQTT is occurring for these 2 but my Android phone is chugging along just fine. I rebooted the ESP32 but no dice.

**Expected behavior**
MQTT messages to keep coming and not suddenly stop.

**Hardware Details**
iPhone 12 Pro latest iOS 15.x and running room-assistant app

**Config**

- [ ] Active Scan enabled
- [ ] Query enabled

**Logs**
NA
**Screenshots**
NA

**Comment by leacho73** [comment] 2022-02-10 12:29
I can confirm that the iPhone 13 also suffers from this random issue - I left my iPhone next to the ESP all day yesterday and today - and get the following results:
![image](https://user-images.githubusercontent.com/54068804/153408760-6052454c-e940-49d9-a53a-092fe7129059.png)

**Comment by jcastro** [comment] 2022-02-10 15:49
Same here! using iPhone 13 Pro + ESP32 Wemos D1 Mini

**Comment by DTTerastar** [comment] 2022-02-11 02:10
What are the ids you're using?

**Comment by k41zen** [comment] 2022-02-11 14:02
I'm using apple:iphone14-2 which is what I do sometimes see in MQTT Explorer. Bluetility shows it too:
![Screenshot 2022-02-11 at 14 01 00](https://user-images.githubusercontent.com/43755140/153605025-bf35264f-4e9c-41d3-8d21-ac90384601dd.png)

**Comment by nickelnine** [comment] 2022-02-11 17:31
Initially "apple:13-3" but after a reboot it appears as "apple:1005:9-12".

**Comment by tobst96** [comment] 2022-02-12 22:42
Same here. Apple don't work. 
iPhone XR
iPhone 11
2 x Apple Watch Series 7

**Comment by DanielBaulig** [comment] 2022-02-13 19:48
I am having trouble with spotty reporting for an iPhone 14 Pro, iPhone XS and an Apple Watch Series 7, too.

**Comment by DTTerastar** [comment] 2022-02-14 19:14
The newest version allows you to selectively decide which ids you want queried to improve the id.  You can now put "apple:1005:9-12" in the query box and it'll ask the phone for it's model and turn it into "apple:13-3".  BUT if apple:1005:9-12 is working for you reliably it's better just to use that and keep query empty.  The ESP32 has to stop listening while sending out the queries which hurts the reliability of receiving advertisements from devices.

**Comment by abreups** [comment] 2022-03-02 00:15
Same issue with iPhone X, iOS 15.3.1 and ESPresense v2.0.34.

**Comment by nickelnine** [comment] 2022-03-23 21:58
Looking at this more closely again, the model for my iPhone - apple:iphone:13-3 is sometimes listed in MQTT and hence successfully reporting and sometimes not - thus the randomness. I have the device ids in the Query field but can't nail down a pattern to the missing model. These are the device ids I set - apple:1005:9-12 apple:1005:9-8 apple:1005:9-26

**Comment by afinzel** [comment] 2022-05-08 13:34
Just wanted to add to this.  It looks like the device fingerprinting doesn't always work.  I have set up room assistant on the devices.  It will work but then I think the mac changes and the device is no longer registering as roomassistant:xxxx-xxx but it has gone back to apple:1006:10-8.  I saw this behaviour by using MQTT explorer and seeing the mac coming up under multiple devices depending on the esp.  Is it easy to debug this code?

**Comment by DTTerastar** [comment] 2022-07-18 06:35
The newest beta has a feature to "Enroll" iOS devices.  We store the BLE IRK and from that point on you can use that irk:{32chars} to uniquely identify that iOS device!

**Comment by afinzel** [comment] 2022-07-18 06:36
That is great news.  Thanks

**Comment by leacho73** [comment] 2022-07-20 10:32
> The newest beta has a feature to "Enroll" iOS devices. We store the BLE IRK and from that point on you can use that irk:{32chars} to uniquely identify that iOS device!

This is great, thanks, when will this Beta be available?

**Comment by DTTerastar** [comment] 2022-07-20 19:08
Check the box labeled "Prerelease" and you'll have it in 5 minutes!

**Comment by leacho73** [comment] 2022-07-21 09:11
Ah cheers @DTTerastar - I am running 2.2.8 - but couldn't see how to interview the apple devices, so assumed I didn't have it :)

**Comment by DTTerastar** [comment] 2022-09-01 14:42
It's released, going to close this.

**Closed by DTTerastar** 2022-09-01 14:42 UTC
Labels: bug
