### ISSUE TITLE
/ui/#/settings page does not show up

### ISSUE THREAD

**Issue by labob246** [ESPresense/ESPresense#1129] opened 2023-11-22 23:28 UTC
### Describe the bug

In version 3.3.1 the /ui/#/settings page does not show (see screenshot).  I have 9 espresense devices and some settings pages show after upgrading some do not.  It does not seem to be the type of device (ESP32 D1 mini or ESP32 Dev board) specific.  All the devices have the same info in them (except for Room) and the default configuration except for filter.  The devices page and fingerprints page work fine.  I have tried 4 browsers, some with fresh installs and it does not seem to help.  Since most options are available in Home Assistant, I don't care, but I do need the change the filters option every now and then and cannot see it.

### Version

3.3.1

### Screenshots

![ESPresense](https://github.com/ESPresense/ESPresense/assets/25141706/7049af7c-98a5-43d7-af0b-ae089065ac98)

**Comment by nybdog** [comment] 2023-11-24 15:14
having the same problem.

**Comment by SheckieJR** [comment] 2023-11-26 20:08
Here as well.  The settings do appear, but then disappear for me.  That led me to believe it was browser or extension related, so I also did that testing, to no avail.
![ESPresense-UI-settings](https://github.com/ESPresense/ESPresense/assets/111116171/e9a6f1d5-e7ac-4ec1-91e3-5021f1d4ceac)

**Comment by sriprasadgit** [comment] 2023-12-06 21:44
havign the same issue, in my one of device

**Comment by jfiggins** [comment] 2023-12-08 22:02
![Screenshot_20231208-170147.png](https://github.com/ESPresense/ESPresense/assets/58125465/23d3ffc1-0604-4c81-b909-7d5227002cac)

Same issue here, only on one of my devices though.

**Comment by ecto1a2003** [comment] 2023-12-18 06:37
All the same here

**Comment by markheitz** [comment] 2023-12-18 22:08
First time with espresence.. just installed and having the same errors also.

**Comment by Schlafenein** [comment] 2023-12-25 03:01
same issue here, only one of three have this issue. all v3.3.1

**Comment by ecto1a2003** [comment] 2023-12-25 03:13
> full erase and reflash seems to fix it for me currently

**Comment by dacorn** [comment] 2023-12-30 07:52
I have the same issue on 5 of 8 units. All have the same version installed. 3.3.1 Do we have an ETA to get this fixed as I need to add more devices to track. Or is there another way to add resolving keys? Thanks guys!!

**Comment by dxmnkd316** [comment] 2024-01-03 22:50
Looks like it has to do with a bad json format.  I accidentally pasted a string with either a tab or extra space into the device filter and it gets hung up on loading the "/extras" string.  

Not sure how to fix it.  That's just what the issue is for me.  

Going to try to reflash, which I'm confident will work.  Just a PITA.

**Comment by roofuskit** [comment] 2024-01-20 15:41
Tested in Firefox and Chrome. Same issue.

**Comment by labob246** [comment] 2024-03-14 19:25
I have updated all 9 of my epresense sensors to 3.3.2 and the problem seems to have disappeared.

**Closed** 2024-09-28 02:27 UTC
Labels: bug, wontfix

**Comment by arbiengine** [comment] 2025-04-18 21:13
I dont think this was resolved, I am still not seeing the settings page after flashing with platform io to my esp32s3 board
